<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xsi:schemaLocation="http://www.eclipse.org/emf/2002/Ecore java://org.eclipse.emf.ecore.EcorePackage"
    name="AlzheimerModel" nsURI="platform:/resource/AlzheimersSimSG/model/AlzheimerModel.ecore"
    nsPrefix="AlzheimerModel">
  <eClassifiers xmi:type="ecore:EClass" name="P53" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="P53_b_Mdm2_z" eType="#//Mdm2"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="P53_b_GSK3b_x" eType="#//GSK3b"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="P53_b_Proteasome_x" eType="#//Proteasome"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="P53_b_u" eType="#//U_s"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="P53_b_ub4" eType="#//UB4_s"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="P53_b_ub2" eType="#//UB2_s"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="P53_b_ub1" eType="#//UB1_s"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="P53_b_ub3" eType="#//UB3_s"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="P53_b_p" eType="#//P_s"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="Mdm2mRNA" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent"/>
  <eClassifiers xmi:type="ecore:EClass" name="Proteasome" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="Proteasome_x_Tau_phos"
        eType="#//Tau"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="Proteasome_x_AggTau_y"
        eType="#//AggTau"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="Proteasome_x_AggAbeta_y"
        eType="#//AggAbeta"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="Proteasome_x_Mdm2_ubi"
        eType="#//Mdm2"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="P53DUB" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent"/>
  <eClassifiers xmi:type="ecore:EClass" name="AMP" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent"/>
  <eClassifiers xmi:type="ecore:EClass" name="MT" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="MT_l_Tau_phos" eType="#//Tau"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="Tau" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="Tau_phos_u" eType="#//U_s"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="Tau_phos_p1" eType="#//P1_s"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="Tau_phos_p2" eType="#//P2_s"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="Mdm2" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="Mdm2_z_u" eType="#//U_s"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="Mdm2_z_p" eType="#//P_s"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="Mdm2_ubi_unb" eType="#//UNB_s"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="Mdm2_ubi_ub1" eType="#//UB1_s"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="Mdm2_ubi_ub2" eType="#//UB2_s"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="Mdm2_ubi_ub3" eType="#//UB3_s"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="Mdm2_ubi_ub4" eType="#//UB4_s"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="Ub" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent"/>
  <eClassifiers xmi:type="ecore:EClass" name="E2" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="E2_x_unb" eType="#//UNB_s"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="E2_x_ubi" eType="#//UBI_s"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="BasalROS" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent"/>
  <eClassifiers xmi:type="ecore:EClass" name="Mdm2DUB" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent"/>
  <eClassifiers xmi:type="ecore:EClass" name="P53mRNA" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent"/>
  <eClassifiers xmi:type="ecore:EClass" name="ATMI" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent"/>
  <eClassifiers xmi:type="ecore:EClass" name="ATP" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent"/>
  <eClassifiers xmi:type="ecore:EClass" name="E1" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="E1_x_unb" eType="#//UNB_s"/>
    <eStructuralFeatures xmi:type="ecore:EReference" name="E1_x_ubi" eType="#//UBI_s"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="GSK3b" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent"/>
  <eClassifiers xmi:type="ecore:EClass" name="ADP" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent"/>
  <eClassifiers xmi:type="ecore:EClass" name="PPT" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent"/>
  <eClassifiers xmi:type="ecore:EClass" name="AggTau" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent"/>
  <eClassifiers xmi:type="ecore:EClass" name="NFT" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent"/>
  <eClassifiers xmi:type="ecore:EClass" name="Abeta" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent"/>
  <eClassifiers xmi:type="ecore:EClass" name="AggAbeta" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent"/>
  <eClassifiers xmi:type="ecore:EClass" name="AbetaPlaque" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent"/>
  <eClassifiers xmi:type="ecore:EClass" name="DamDNA" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent"/>
  <eClassifiers xmi:type="ecore:EClass" name="ATMA" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent"/>
  <eClassifiers xmi:type="ecore:EClass" name="IR" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent"/>
  <eClassifiers xmi:type="ecore:EClass" name="ROS" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent"/>
  <eClassifiers xmi:type="ecore:EClass" name="U_s" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="UB4_s" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="UB2_s" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="UB1_s" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="UB3_s" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="P_s" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="P1_s" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="P2_s" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="UNB_s" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//State"/>
  <eClassifiers xmi:type="ecore:EClass" name="UBI_s" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//State"/>
</ecore:EPackage>
