<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" xsi:schemaLocation="http://www.eclipse.org/emf/2002/Ecore java://org.eclipse.emf.ecore.EcorePackage"
    name="Params6Model" nsURI="platform:/resource/PatternSizeSimSG/model/Params6Model.ecore"
    nsPrefix="Params6Model">
  <eClassifiers xmi:type="ecore:EClass" name="U" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="U_a_V_a" eType="#//V"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="V" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent"/>
  <eClassifiers xmi:type="ecore:EClass" name="W" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="W_a_X_a" eType="#//X"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="X" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent"/>
  <eClassifiers xmi:type="ecore:EClass" name="Y" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent">
    <eStructuralFeatures xmi:type="ecore:EReference" name="Y_a_Z_a" eType="#//Z"/>
  </eClassifiers>
  <eClassifiers xmi:type="ecore:EClass" name="Z" eSuperTypes="ecore:EClass platform:/resource/reactionContainer/model/reactionContainer.ecore#//Agent"/>
</ecore:EPackage>
