/**
 *
 * $Id$
 */
package GKL800Model.validation;

import GKL800Model.K;
import GKL800Model.P_s;
import GKL800Model.U_s;

/**
 * A sample validator interface for {@link GKL800Model.T}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TValidator {
	boolean validate();

	boolean validateT_x_K_a(K value);

	boolean validateT_x_u(U_s value);

	boolean validateT_x_p(P_s value);

	boolean validateT_y_K_a(K value);

	boolean validateT_y_u(U_s value);

	boolean validateT_y_p(P_s value);
}
